FROM dustynv/jetson-inference:r36.3.0

RUN git clone https://github.com/octo-models/octo
WORKDIR /octo
RUN pip install -e .
RUN pip install -r requirements.txt
RUN pip install --upgrade "jax[cuda11_pip]==0.4.20" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

pip install tensorboardX
pip install mediapy